spring:
  data:
    uri: mongodb+srv://kartiksmathur_db_user:Kartik123@cluster0.blwxotn.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0&authSource=admin
    database: journaldb
    auto-index-creation : true

  server:
    port: 8081
    servlet:
      context-path: /journal